export const RHYTHM_COMMAND_TYPES = Object.freeze({
  TAP: "tap",
  HOLD: "hold",
  MASH: "mash",
});

export const RHYTHM_DISH_LEVELS = Object.freeze([
  Object.freeze({
    id: "genki-fried-egg",
    title: "元气煎蛋",
    dishName: "元气煎蛋",
    durationMs: 30_000,
    commands: Object.freeze([
      {
        id: "crack-egg",
        input: RHYTHM_COMMAND_TYPES.TAP,
        actionName: "敲蛋",
        prompt: "敲蛋！",
        helperText: "看准节奏点击",
        startAtMs: 800,
        targetAtMs: 1_500,
        expireAtMs: 2_200,
      },
      {
        id: "whisk-egg",
        input: RHYTHM_COMMAND_TYPES.MASH,
        actionName: "打蛋",
        prompt: "快速打蛋！",
        helperText: "时间内狂点",
        startAtMs: 2_650,
        endAtMs: 5_050,
        targetTaps: 8,
      },
      {
        id: "pour-pan",
        input: RHYTHM_COMMAND_TYPES.TAP,
        actionName: "下锅",
        prompt: "下锅！",
        helperText: "进命中区再点",
        startAtMs: 5_600,
        targetAtMs: 6_300,
        expireAtMs: 7_000,
      },
      {
        id: "fry-egg",
        input: RHYTHM_COMMAND_TYPES.HOLD,
        actionName: "煎蛋",
        prompt: "按住煎！",
        helperText: "按住到目标区松开",
        startAtMs: 7_450,
        targetAtMs: 8_650,
        targetHoldMs: 1_200,
        expireAtMs: 10_200,
      },
      {
        id: "salt-egg",
        input: RHYTHM_COMMAND_TYPES.TAP,
        actionName: "撒盐",
        prompt: "撒盐！",
        helperText: "轻点一下调味",
        startAtMs: 10_700,
        targetAtMs: 11_400,
        expireAtMs: 12_100,
      },
      {
        id: "stir-fry",
        input: RHYTHM_COMMAND_TYPES.MASH,
        actionName: "翻炒",
        prompt: "快速翻炒！",
        helperText: "连点制造锅气",
        startAtMs: 12_650,
        endAtMs: 15_250,
        targetTaps: 9,
      },
      {
        id: "control-fire",
        input: RHYTHM_COMMAND_TYPES.HOLD,
        actionName: "控火",
        prompt: "控火！",
        helperText: "按住稳火，到点松开",
        startAtMs: 15_850,
        targetAtMs: 17_050,
        targetHoldMs: 1_200,
        expireAtMs: 18_600,
      },
      {
        id: "serve-egg",
        input: RHYTHM_COMMAND_TYPES.TAP,
        actionName: "出锅",
        prompt: "出锅！",
        helperText: "最后一下装盘",
        startAtMs: 19_250,
        targetAtMs: 20_000,
        expireAtMs: 20_800,
      },
    ]),
  }),
  Object.freeze({
    id: "golden-egg-mix",
    title: "黄金蛋液",
    dishName: "黄金蛋液",
    durationMs: 24_000,
    commands: Object.freeze([
      { id: "gold-crack", input: RHYTHM_COMMAND_TYPES.TAP, actionName: "敲蛋", prompt: "敲蛋！", helperText: "看准节奏点击", startAtMs: 800, targetAtMs: 1_500, expireAtMs: 2_200 },
      { id: "gold-stir", input: RHYTHM_COMMAND_TYPES.MASH, actionName: "搅拌", prompt: "快速搅拌！", helperText: "时间内狂点", startAtMs: 2_700, endAtMs: 5_000, targetTaps: 8 },
      { id: "gold-warm", input: RHYTHM_COMMAND_TYPES.HOLD, actionName: "保温", prompt: "按住保温！", helperText: "按住到目标区松开", startAtMs: 5_600, targetAtMs: 6_800, targetHoldMs: 1_200, expireAtMs: 8_300 },
      { id: "gold-pour", input: RHYTHM_COMMAND_TYPES.TAP, actionName: "倒入锅中", prompt: "倒入锅中！", helperText: "进命中区再点", startAtMs: 8_900, targetAtMs: 9_650, expireAtMs: 10_400 },
      { id: "gold-fast-stir", input: RHYTHM_COMMAND_TYPES.MASH, actionName: "快速搅拌", prompt: "快速搅拌！", helperText: "连点打出金色蛋液", startAtMs: 11_000, endAtMs: 13_500, targetTaps: 9 },
      { id: "gold-finish", input: RHYTHM_COMMAND_TYPES.TAP, actionName: "完成", prompt: "完成！", helperText: "最后一下定型", startAtMs: 14_100, targetAtMs: 14_850, expireAtMs: 15_600 },
    ]),
  }),
  Object.freeze({
    id: "breakfast-plate",
    title: "早餐拼盘",
    dishName: "早餐拼盘",
    durationMs: 22_000,
    commands: Object.freeze([
      { id: "toast-place", input: RHYTHM_COMMAND_TYPES.TAP, actionName: "放面包", prompt: "放面包！", helperText: "看准节奏点击", startAtMs: 800, targetAtMs: 1_450, expireAtMs: 2_100 },
      { id: "toast-bake", input: RHYTHM_COMMAND_TYPES.HOLD, actionName: "烘烤", prompt: "按住烘烤！", helperText: "按住到目标区松开", startAtMs: 2_650, targetAtMs: 3_850, targetHoldMs: 1_200, expireAtMs: 5_300 },
      { id: "plate-egg", input: RHYTHM_COMMAND_TYPES.TAP, actionName: "加蛋", prompt: "加蛋！", helperText: "进命中区再点", startAtMs: 5_900, targetAtMs: 6_600, expireAtMs: 7_300 },
      { id: "plate-arrange", input: RHYTHM_COMMAND_TYPES.MASH, actionName: "摆盘", prompt: "快速摆盘！", helperText: "时间内狂点", startAtMs: 7_900, endAtMs: 10_300, targetTaps: 8 },
      { id: "plate-serve", input: RHYTHM_COMMAND_TYPES.TAP, actionName: "出餐", prompt: "出餐！", helperText: "最后一下上桌", startAtMs: 10_950, targetAtMs: 11_700, expireAtMs: 12_500 },
    ]),
  }),
]);

export const RHYTHM_TEST_LEVEL = RHYTHM_DISH_LEVELS[0];
